### ISSUE TITLE
Qt5.5  ‘setCodecForCStrings’ is not a member of ‘QTextCodec’

### ISSUE THREAD

**Issue by Golutazem** [kmingulov/JapanTables#1]
Error compiling with Qt5.5.
main.cpp:14:5: error: ‘setCodecForCStrings’ is not a member of ‘QTextCodec’

**Comment by kmingulov** [comment]
Hello, @edakiri. Thank you for your issue report. This program was written in Qt4 and hasn't yet been ported to Qt5.

If the only thing you need is JapanTables binaries, let me know and I will upload them to GitHub.
